import asyncio
from typing import List, Dict
from app.core.engine import OpusEngine
from app.utils.logger import log

class Agent:
    def __init__(self, name: str, role: str, engine: OpusEngine):
        self.name = name
        self.role = role
        self.engine = engine
    
    async def execute(self, task: str) -> str:
        """
        Agent performs a specific sub-task.
        """
        log(f"[{self.name} - {self.role}] starting task: {task[:30]}...", "INFO")
        
        # Each agent uses the main engine but with specific system instructions
        prompt = f"Role: {self.role}. Task: {task}. Output specific deliverables."
        response = await self.engine.chat(prompt, effort="high")
        
        log(f"[{self.name}] finished.", "INFO")
        return response

class SwarmOrchestrator:
    def __init__(self, engine: OpusEngine):
        self.engine = engine
        self.agents: List[Agent] = []

    def add_agent(self, name: str, role: str):
        self.agents.append(Agent(name, role, self.engine))

    async def run_mission(self, objective: str):
        """
        Main loop for the Swarm. Orchestrates agents to solve the objective.
        """
        log(f"Starting Swarm Mission: {objective}", "GODMODE")
        
        # Step 1: Planning
        plan = await self.engine.chat(f"Create a step-by-step plan for: {objective}", effort="max")
        log("Plan generated by Orchestrator.", "INFO")

        # Step 2: Parallel Execution (Simulation)
        tasks = []
        for agent in self.agents:
            # Assigning a generic task for demo purposes
            task_desc = f"Contribute to objective '{objective}' based on your role."
            tasks.append(agent.execute(task_desc))
        
        results = await asyncio.gather(*tasks)
        
        # Step 3: Synthesis
        log("Aggregating results from all agents...", "INFO")
        final_summary = await self.engine.chat(f"Merge these results: {results}", effort="medium")
        
        log("Mission Complete.", "GODMODE")
        return final_summary
